In [46]:
from layers.QonvLayer import QonvLayer
from torch import nn
import torchvision
import torch
from tqdm.auto import tqdm
from sklearn.metrics import accuracy_score

In [11]:
qonv = QonvLayer(kernel_size = 4, circuit_layers=2, n_rotations=16, wires = 16, out_channels=16, stride=3)

In [12]:
x = torch.rand(size=(10,64,64,3))
qonv(x).shape

torch.Size([10, 21, 21, 16])

In [15]:
model = torch.nn.Sequential(
        QonvLayer(kernel_size = 4, circuit_layers=2, n_rotations=4, wires = 16, out_channels=16, stride=3),
        torch.nn.Flatten(),
        torch.nn.Linear(in_features=21*21*16, out_features=10)
    )

model.train()
optimizer = torch.optim.Adam(params=model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()

In [41]:
import matplotlib.pyplot as plt
import numpy as np
import glob
import os

images, labels, classes = [], [], []

class_folders = glob.glob(os.path.join('datasets/EuroSAT', '*'))
class_folders.sort()

for i, c in enumerate(tqdm(class_folders)):
    classes.append(c.split(os.sep)[-1])
    for _, ip in enumerate(glob.glob(os.path.join(c, '*'))):
        img = plt.imread(ip)/255.0
        #img = torch.from_numpy(x).float()
        images.append(img)
        labels.append(i)
        
images = np.array(images)
labels = np.array(labels)
images = torch.Tensor(images)
labels = torch.Tensor(labels).type(torch.LongTensor)

  0%|          | 0/10 [00:00<?, ?it/s]

In [ ]:
epochs = 1
batch_size = 10

for epoch in range(epochs):
    # remember to shuffle    
    for j in range((len(labels)//batch_size) - batch_size):
        x = images[j*batch_size:(j+1)*batch_size, ...]
        y = labels[j*batch_size:(j+1)*batch_size, ...]
        
        # reset optimizer
        optimizer.zero_grad()

        # engage
        y_pred = model(x)

        # error, gradients and optimization
        loss = criterion(y_pred, y)  
        loss.backward()
        optimizer.step()

        # output
        acc = accuracy_score(y, y_pred.argmax(-1).numpy())       

        print("Epoch:", epoch, "\tStep:", j, "\tAccuracy:", acc, "\tLoss:", loss.item())
        #print("Gradients Layer 0:")
        #print(model[0].circuit.weights.grad)

        #if i % 5 == 0:
        #    model[0].draw()

        print("---------------------------------------")

        # early break
        #if i > 0 and i % 10 == 0:
        #    break

Epoch: 0 	Step: 0 	Accuracy: 1.0 	Loss: 1.3947383195045404e-05
Gradients Layer 0:
tensor([[-6.2341e-06, -2.3557e-05, -6.1270e-06,  9.1177e-14],
        [-2.3834e-05, -5.3291e-15, -1.1319e-06, -1.1013e-13]])
---------------------------------------
Epoch: 0 	Step: 0 	Accuracy: 1.0 	Loss: 1.1205665941815823e-06
Gradients Layer 0:
tensor([[-5.5204e-07, -2.0884e-06, -5.4455e-07,  4.5103e-15],
        [-2.1321e-06, -3.3529e-14, -9.0502e-08,  4.2188e-15]])
---------------------------------------
Epoch: 0 	Step: 0 	Accuracy: 1.0 	Loss: 2.384185648907078e-08
Gradients Layer 0:
tensor([[-3.8039e-08, -1.5801e-07, -4.1634e-08,  3.8923e-16],
        [-1.7503e-07,  9.4369e-16,  1.9804e-09, -1.0408e-15]])
---------------------------------------


[E thread_pool.cpp:113] Exception in thread pool task: mutex lock failed: Invalid argument


In [ ]:
y_pred